name: openwrt-xiaomi4a-stable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y wget tar xz-utils git

      - name: Download ImageBuilder
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt76x8/openwrt-imagebuilder-23.05.3-ramips-mt76x8.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-23.05.3-ramips-mt76x8.Linux-x86_64.tar.xz
          mv openwrt-imagebuilder-23.05.3-ramips-mt76x8.Linux-x86_64 builder

      - name: Add tweaks
        run: |
          mkdir -p builder/files/etc/sysctl.d
          mkdir -p builder/files/etc/config

          echo "net.core.netdev_max_backlog=8192" > builder/files/etc/sysctl.d/99-network.conf
          echo "net.netfilter.nf_conntrack_max=32768" >> builder/files/etc/sysctl.d/99-network.conf

          echo "config globals" > builder/files/etc/config/network
          echo "    option packet_steering '1'" >> builder/files/etc/config/network

      - name: Build firmware
        run: |
          cd builder
          make image PROFILE=xiaomi_mi-router-4a-100m FILES=files PACKAGES="luci htop nano irqbalance kmod-usb-core kmod-usb2 kmod-usb-storage kmod-usb-net kmod-usb-net-rndis usb-modeswitch block-mount kmod-fs-ext4 kmod-fs-vfat kmod-fs-ntfs3 samba4-server luci-app-samba4 mwan3 luci-app-mwan3 -ppp -ppp-mod-pppoe -ipv6helper -odhcpd-ipv6only"

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-xiaomi4a
          path: builder/bin/targets/
