name: openwrt-xiaomi4a-ultra

on:
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: install tools
    run: |
      sudo apt update
      sudo apt install -y wget tar xz-utils git

  - name: download imagebuilder
    run: |
      wget https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt76x8/openwrt-imagebuilder-23.05.3-ramips-mt76x8.Linux-x86_64.tar.xz
      tar -xf openwrt-imagebuilder*
      mv openwrt-imagebuilder* builder

  - name: clone extra packages
    run: |
      git clone https://github.com/amnezia-vpn/amneziawg-openwrt builder/packages/amneziawg
      git clone https://github.com/bol-van/zapret builder/packages/zapret

  - name: build firmware
    run: |
      cd builder
      make image PROFILE=xiaomi_mi-router-4a-100m FILES=files PACKAGES="\
      kmod-usb-core \
      kmod-usb2 \
      kmod-usb-storage \
      kmod-usb-net \
      kmod-usb-net-rndis \
      usb-modeswitch \
      block-mount \
      kmod-fs-ext4 \
      mwan3 \
      amneziawg \
      -ppp \
      -ppp-mod-pppoe \
      -firewall4 \
      -dnsmasq \
      -odhcpd-ipv6only \
      -ip6tables \
      -luci"

  - name: upload firmware
    uses: actions/upload-artifact@v4
    with:
      name: xiaomi4a-ultra
      path: builder/bin/targets/
```
